### PR TITLE
Finished the problems

### PR DESCRIPTION
**Pull request by AlexLister**

### CODE REVIEW

**Comment by BenKnowlson18** [comment]
why did you comment on your own post with a laugh emoji you scrub. :100: :+1: :1st_place_medal:

**Comment by AlexLister** [comment]
Leave my page before I click report abuse

**Comment by BenKnowlson18** [comment]
click it I dare you :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:  :100:

**Comment by AlexLister** [comment]
:(

**Comment by AlexLister** [comment]
reported you nerd

**Pull request closed without merging**
